// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwiftSteamGameApi.Data;

#nullable disable

namespace SwiftSteamGameApi.Data.Migrations
{
    [DbContext(typeof(GameLibraryDbContext))]
    [Migration("20260626100840_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearOfRelease")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId")
                        .IsUnique();

                    b.ToTable("GameDetails");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameDetailsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameDetailsId");

                    b.HasIndex("GameRecordId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameRecords");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cons")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DifficultyRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FavoriteMoment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PersonalRating")
                        .HasPrecision(3, 1)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pros")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplayValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewBody")
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId")
                        .IsUnique();

                    b.ToTable("GameReviews");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId");

                    b.ToTable("GameTags");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.PersonalTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPlayed")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursPlayed")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInBacklog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WantsReplay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId")
                        .IsUnique();

                    b.ToTable("PersonalTrackings");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.Related.GameAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId");

                    b.ToTable("GameAchievements");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.Related.GameCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId");

                    b.ToTable("GameCategories");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.Related.GameScreenshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameRecordId");

                    b.ToTable("GameScreenshots");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameDetails", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithOne("Details")
                        .HasForeignKey("SwiftSteamGameApi.Models.GameDetails", "GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameGenre", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameDetails", "GameDetails")
                        .WithMany("Genres")
                        .HasForeignKey("GameDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithMany()
                        .HasForeignKey("GameRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameDetails");

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameReview", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithOne("Review")
                        .HasForeignKey("SwiftSteamGameApi.Models.GameReview", "GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameTag", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithMany("Tags")
                        .HasForeignKey("GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.PersonalTracking", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithOne("Tracking")
                        .HasForeignKey("SwiftSteamGameApi.Models.PersonalTracking", "GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.Related.GameAchievement", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithMany("Achievements")
                        .HasForeignKey("GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.Related.GameCategory", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithMany("Categories")
                        .HasForeignKey("GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.Related.GameScreenshot", b =>
                {
                    b.HasOne("SwiftSteamGameApi.Models.GameRecord", "GameRecord")
                        .WithMany("Screenshots")
                        .HasForeignKey("GameRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameRecord");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameDetails", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("SwiftSteamGameApi.Models.GameRecord", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Categories");

                    b.Navigation("Details")
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Screenshots");

                    b.Navigation("Tags");

                    b.Navigation("Tracking")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
